### ISSUE TITLE
GUI assets are missing.

### ISSUE THREAD

**Issue by rayanfer32** [hackerminds/DICTO-WRITTER#3]
```sh
Traceback (most recent call last):
  File "dictoWriterGUI.py", line 211, in <module>
    root.iconbitmap(icon_path)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "E:\Visual_Studio_Code\python\GUI\Dicto-Writter_small.ico" not defined

```

**Comment by shrivatsabhat** [comment]
Thank you reminding

**Comment by shrivatsabhat** [comment]
the issue is solved.  But considering the raspberry pi OS, this GUI is made. So in windows, it may show some errors.
